### 

### 1. Numpy N-Dimesion Array(nd array)

In [2]:
# numpy 쓸 땐 항상 import 해줘야 함
import numpy as np

- nd array와 list의 차이

In [3]:
# 제곱수 리스트 만들기(기존 버전)
l = [1,2,3,4,5]
l = [i*i for i in l]
l

[1, 4, 9, 16, 25]

In [4]:
# numpy 버전
# array를 생성
n = np.array([1,2,3,4,5], dtype=int)
n

array([1, 2, 3, 4, 5])

In [5]:
# 제곱수 만들기
# 반복문 없이 빠르게 전체에 대해 오퍼레이션을 실행할 수 있다.
n = np.square(n)
n

array([ 1,  4,  9, 16, 25])

- 1차원 배열(vector)

In [6]:
# nd array의 타입
a = np.array([1,2,3,4,5,6,7,8,9,10])
type(a)

numpy.ndarray

In [7]:
# nd array의 속성
a.dtype, a.shape, a.ndim, a.size

(dtype('int32'), (10,), 1, 10)

- array에 대해 다음과 같은 계산도 가능하다

In [8]:
# 벡터화 연산
# 각 2배씩 곱하기
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
a = np.array([1,2,3])
b = np.array([10,20,30])
c = 2 * a + b
c

array([12, 24, 36])

In [10]:
a == 2, b > 10

(array([False,  True, False]), array([False,  True,  True]))

- 2차원 배열(Matrix)

In [11]:
c = np.array([[1,2,3],[4,5,6]]) # np.arange(1,7).reshape(2,3)
print(c)

[[1 2 3]
 [4 5 6]]


In [12]:
# c의 타입, c의 쉐잎(), c의 엘리먼트의 갯수
c.dtype, c.shape, c.size

(dtype('int32'), (2, 3), 6)

- 3차원 배열(Tensor)

In [13]:
t = np.arange(1, 25).reshape(2, 3, 4)
t

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [14]:
t.dtype, t.shape, t.ndim, t.size

(dtype('int32'), (2, 3, 4), 3, 24)

- 배열의 인덱싱

In [15]:
a

array([1, 2, 3])

In [16]:
a[0], a[2], a[-1]

(1, 3, 3)

In [17]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
# numpy에서는 다음처럼 인덱싱 할 수 있다
c[0,0], c[-1,0], c[1,2]

(1, 4, 6)

- 배열의 슬라이싱

In [19]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l[:2]

[[1, 2, 3], [4, 5, 6]]

In [20]:
# 기존에 하던 방식 (작동 안됨)
# 리스트에서는 행과 열로 동시에 슬라이싱이 안된다.
l[:2][1:]

[[4, 5, 6]]

In [21]:
c = np.arange(1,10).reshape(3,3)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
# 위 두 행
c[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
# 오른쪽 두 열
# :만 쓰면 모든 행/열에 대해 적용시킴
c[:, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [24]:
# 5,6,8,9를 출력
c[1:,1:]

array([[5, 6],
       [8, 9]])

In [25]:
# 1,4,3,6
c[:-1, ::2]

array([[1, 3],
       [4, 6]])

- 연습문제

In [26]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [27]:
m[1:-1, 2:-2]

array([[7]])

In [28]:
m[2:, -1:]

array([[14]])

In [29]:
m[1:2, 1:3]

array([[6, 7]])

In [30]:
m[1:3, 2:3]

array([[ 7],
       [12]])

In [31]:
m[:1, 3:], m[1:2, 3:]

(array([[3, 4]]), array([[8, 9]]))

- 해답

In [32]:
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
m[1,2], m[-1,-1], m[1,1:3], m[1:, 2], m[:-1,3:]

(7,
 14,
 array([6, 7]),
 array([ 7, 12]),
 array([[3, 4],
        [8, 9]]))

- 배열 인덱싱

In [34]:
# idx값이 True/False면 True값이 있는 곳만 통과

In [35]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
               False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [36]:
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [37]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [38]:
a[a%2 == 1]

array([1, 3, 5, 7, 9])

In [39]:
# idx 값이 정수값(인덱스)이면 해당 인덱스의 원소가 선택됨
idx = np.array([1, 3, 5, 7, 9])
a[idx]

array([1, 3, 5, 7, 9])

- 연습문제

In [40]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [41]:
x[x%3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [42]:
x[x%4 == 1]

array([ 1,  5,  9, 13, 17])

In [43]:
x[(x%3==0) & (x%4 == 1)]

array([9])

In [44]:
# 위에서 구한 결과는 ndarray임. 원소의 밸류를 다시 꺼내려면 다시 인덱싱 해야함
x[8], x[(x%3==0) & (x%4 == 1)][0]

(9, 9)