### 3. 배열의 연산(Operation)

In [1]:
import numpy as np

- 벡터화 연산

In [4]:
x = np.arange(1, 101)
y = np.arange(1101, 1201)

In [5]:
# 같은 위치의 원소끼리 더해진다
z = x + y
z[:5]

array([1102, 1104, 1106, 1108, 1110])

In [6]:
z = 3 * x
z[:5]

array([ 3,  6,  9, 12, 15])

In [7]:
# 논리연산도 가능하다
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [8]:
a > b

array([False, False,  True, False])

In [9]:
np.log(a), np.exp(a)

(array([0.        , 0.69314718, 1.09861229, 1.38629436]),
 array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003]))

In [10]:
c = np.arange(6).reshape(2,3)
np.exp(c)

array([[  1.        ,   2.71828183,   7.3890561 ],
       [ 20.08553692,  54.59815003, 148.4131591 ]])

In [11]:
c + 3

array([[3, 4, 5],
       [6, 7, 8]])

- 차원 축소 연산

In [12]:
x = np.arange(1,5)
np.sum(x)

10

In [13]:
# 이렇게도 쓸 수 있다
x.sum()

10

In [14]:
# 최소값, 최대값, 평균값
x.min(), x.max(), x.mean()

(1, 4, 2.5)

In [15]:
# 대표값 : 평균, 중앙값
x.mean(), np.median(x)

(2.5, 2.5)

- all or any
    - all : 모든 원소가 다 True인가
    - any : True가 최소 1개라도 있는가

In [16]:
np.all(np.array([True, False, True]))

False

In [17]:
np.any(np.array([True, False, True]))

True

- 2차원 이상의 연산

In [18]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
# 모든 원소의 합, 평균
np.sum(a), np.mean(a)

(21, 3.5)

In [24]:
# 행 방향으로 합/평균을 구하기 (axis=0 : 수직 연산)
np.sum(a, axis=0), np.mean(a, axis=0)

(array([5, 7, 9]), array([2.5, 3.5, 4.5]))

In [25]:
# 열 방향으로 합/평균을 구하기 (axis=1 : 수평 연산)
np.sum(a, axis=1), np.mean(a, axis=1)

(array([ 6, 15]), array([2., 5.]))

- argmax, argmin
    - 최대/최소값의 위치

In [31]:
x = np.array([3,12,33,9,51,26])
np.argmax(x), np.argmin(x)

(4, 0)

In [34]:
y = x.reshape(2,3)
y

array([[ 3, 12, 33],
       [ 9, 51, 26]])

In [35]:
np.argmax(y, axis=0), np.argmin(y, axis=0)

(array([1, 1, 0], dtype=int64), array([0, 0, 1], dtype=int64))

- 연습문제

In [37]:
a = np.arange(1,31).reshape(5,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [44]:
a.max(), np.sum(a, axis=1), a.max(axis=1), np.mean(a,axis=0), np.min(a,axis=0)

(30,
 array([ 21,  57,  93, 129, 165]),
 array([ 6, 12, 18, 24, 30]),
 array([13., 14., 15., 16., 17., 18.]),
 array([1, 2, 3, 4, 5, 6]))

In [43]:
# 무작위 배열 만들기
import random
np.set_printoptions(precision=4,suppress=True)
np.random.seed(2023)
m = np.random.random(30).reshape(5,6)
m

array([[0.322 , 0.8904, 0.5881, 0.1266, 0.1413, 0.4679],
       [0.0221, 0.7273, 0.5244, 0.5449, 0.4564, 0.5014],
       [0.3945, 0.1512, 0.3609, 0.1621, 0.338 , 0.1803],
       [0.391 , 0.0356, 0.5649, 0.2035, 0.3206, 0.3766],
       [0.1841, 0.104 , 0.4549, 0.1959, 0.3785, 0.9305]])