### 5. 난수 발생과 카운팅

In [1]:
import numpy as np

- seed 설정

In [2]:
np.random.seed(2023)
np.random.random(5)

array([0.3219883 , 0.89042245, 0.58805226, 0.12659609, 0.14134122])

In [3]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# 원소 섞기
np.random.shuffle(x)
x

array([8, 1, 9, 2, 3, 0, 5, 6, 7, 4])

- 데이터의 샘플링

In [7]:
# choice(a, b) : a개 중 b개 선택
np.random.choice(5, 5, replace=False)

array([3, 2, 4, 0, 1])

In [10]:
x = np.random.randint(1, 100, 10)
x

array([35, 12,  2, 32, 70, 52, 20, 41, 70, 32])

In [11]:
np.random.choice(x, 5, replace=False)

array([41, 70, 35, 20, 12])

- 난수 생성

In [12]:
# random() : Uniform 분포(공평하게 뽑아냄), 0~1 사이 값
np.random.random(10)

array([0.39172036, 0.11004811, 0.9127915 , 0.35700599, 0.41296218,
       0.18354969, 0.58599027, 0.85567085, 0.78968122, 0.08784242])

In [13]:
# randint(low, high, N) : low ~ high(high는 미포함) 중 N개
np.random.randint(1,7,10)

array([5, 3, 5, 1, 5, 2, 4, 5, 1, 5])

In [14]:
# normal(평균, 표준편차, N) : 평균 +- 표준편차의 값을 N개 출력 (정규분포)
np.random.normal(170, 10, 10)

array([181.67226207, 163.97585636, 166.24095837, 167.08713359,
       160.01620207, 176.03242369, 166.58776424, 169.65713669,
       183.31161153, 157.14453006])

In [15]:
# randn(N) - 표준정규분포 N(0,1)
np.random.randn(10)

array([ 0.55215289,  1.09259703,  1.77210263, -0.1137414 , -1.39798223,
       -0.38444907,  0.45366873, -1.01517303,  0.16824259, -1.26226678])

In [16]:
# binomial(시도횟수, 평균, N) - 이항분포 B(N, p)
np.random.binomial(10,0.5,20).reshape(4,5)

array([[5, 6, 8, 4, 6],
       [5, 5, 6, 2, 1],
       [6, 6, 4, 7, 3],
       [4, 3, 6, 6, 2]])

In [17]:
# t-검정
# standard_t(자유도, N)
np.random.standard_t(2,10)

array([-4.69351722,  0.87950312, 13.60655061, -0.26102413, -1.32482054,
       -1.26550017, -0.82598883, -1.17519698,  0.63656836, -1.01826889])

- 연습문제 3.5.1

In [20]:
# 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 파이썬으로 작성한다.
np.random.binomial(1, 0.5, 10)

array([1, 0, 1, 1, 0, 0, 1, 1, 0, 1])

In [22]:
# 주사위를 100번 던져서 나오는 숫자의 평균을 구하라.
np.mean(np.random.randint(1,7,100))

3.67

In [25]:
# 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 
# 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하라
rate =np.random.normal(0, 0.01, 5)
rate


array([-0.00164069,  0.00926134,  0.00070765,  0.01765456,  0.00222688])

In [27]:
price = 10000
price = price + price * rate[0]
int(np.round(price))

9984

In [29]:
price = 10000
for i in range(5):
    price = price * (1 + rate[i])
    price = int(np.round(price))
    print(price, end=' ')

9984 10076 10083 10261 10284 

In [31]:
np.random.seed(2023)
rate = np.random.normal(0,0.01,250)
rate[:5]

array([ 0.00711674, -0.00324485, -0.01001871,  0.00236251, -0.0010216 ])

In [32]:
# 1. 리스트로 해결
price = 10000
price_list = []
for i in range(250):
    price = price * (1 + rate[i])
    price = int(np.round(price))
    price_list.append(price)

price_array = np.array(price_list)
price_array[-10:]

array([10814, 10893, 10674, 10645, 10588, 10724, 10739, 10686, 10691,
       10497])

In [37]:
# 2. array로 해결
price = 10000
price_array2 = np.zeros(250, dtype=int)
for i in range(250):
    price = price * (1 + rate[i])
    price = int(np.round(price))
    price_array2[i] = price

price_array2[-10:]

array([10814, 10893, 10674, 10645, 10588, 10724, 10739, 10686, 10691,
       10497])

- 데이터 카운팅

In [38]:
# unique : 데이터 중 중복된 값을 제거함 
dices = np.random.randint(1,7,100)
np.unique(dices)

array([1, 2, 3, 4, 5, 6])

In [40]:
indices, count = np.unique(dices, return_counts=True)
indices, count

(array([1, 2, 3, 4, 5, 6]), array([ 9, 24, 24, 13, 15, 15], dtype=int64))

In [43]:
dices_mean = np.sum(indices * count) / np.sum(count)
dices_mean

3.46

In [44]:
np.bincount(dices, minlength=6)

array([ 0,  9, 24, 24, 13, 15, 15], dtype=int64)